import { api } from '@/lib/api';

export interface AssistantRequest {
  prompt: string;
  data: any;
  model?: string;
  max_tokens?: number;
  temperature?: number;
}

export interface AssistantResponse {
  success: boolean;
  response: string;
}

// Comprehensive static data for KP D3
export const KP_FLOODS_STATIC_DATA = {

  incidentReport: [
    {
        "ReportDate": null,
        "DistrictId": 1,
        "DistrictName": "Mardan",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 1,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 1,
        "MaleInjured": 3,
        "FemaleInjured": 0,
        "ChildInjured": 1,
        "TotalInjured": 4,
        "HouseDamagedFully": 2,
        "HouseDamagedPartially": 12,
        "TotalHousesDamaged": 14,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 1,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 2,
        "DistrictName": "Swabi",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 19,
        "FemaleDeaths": 14,
        "ChildDeaths": 9,
        "TotalDeaths": 42,
        "MaleInjured": 3,
        "FemaleInjured": 2,
        "ChildInjured": 1,
        "TotalInjured": 6,
        "HouseDamagedFully": 47,
        "HouseDamagedPartially": 61,
        "TotalHousesDamaged": 108,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 1,
        "TotalSchoolDamaged": 1,
        "TotalOtherDamaged": 0,
        "CattlePerished": 31,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 4,
        "DistrictName": "Charsadda",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 1,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 1,
        "HouseDamagedFully": 1,
        "HouseDamagedPartially": 8,
        "TotalHousesDamaged": 9,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 5,
        "DistrictName": "Nowshera",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 1,
        "FemaleDeaths": 1,
        "ChildDeaths": 0,
        "TotalDeaths": 2,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 2,
        "TotalHousesDamaged": 2,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 7,
        "DistrictName": "Mohmand",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 1,
        "ChildInjured": 0,
        "TotalInjured": 1,
        "HouseDamagedFully": 4,
        "HouseDamagedPartially": 16,
        "TotalHousesDamaged": 20,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 1,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 8,
        "DistrictName": "Bajaur",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 2,
        "FemaleDeaths": 4,
        "ChildDeaths": 16,
        "TotalDeaths": 22,
        "MaleInjured": 2,
        "FemaleInjured": 4,
        "ChildInjured": 0,
        "TotalInjured": 6,
        "HouseDamagedFully": 9,
        "HouseDamagedPartially": 61,
        "TotalHousesDamaged": 70,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 3,
        "TotalSchoolDamaged": 3,
        "TotalOtherDamaged": 4,
        "CattlePerished": 87,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 9,
        "DistrictName": "Buner",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 71,
        "FemaleDeaths": 115,
        "ChildDeaths": 51,
        "TotalDeaths": 237,
        "MaleInjured": 58,
        "FemaleInjured": 62,
        "ChildInjured": 8,
        "TotalInjured": 128,
        "HouseDamagedFully": 276,
        "HouseDamagedPartially": 1374,
        "TotalHousesDamaged": 1650,
        "SchoolDamagedFully": 1,
        "SchoolDamagedPartially": 28,
        "TotalSchoolDamaged": 29,
        "TotalOtherDamaged": 0,
        "CattlePerished": 4405,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 11,
        "DistrictName": "Upper-Chitral",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 5,
        "HouseDamagedPartially": 0,
        "TotalHousesDamaged": 5,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 13,
        "DistrictName": "Lower Dir",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 2,
        "ChildDeaths": 3,
        "TotalDeaths": 5,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 3,
        "HouseDamagedPartially": 44,
        "TotalHousesDamaged": 47,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 2,
        "TotalSchoolDamaged": 2,
        "TotalOtherDamaged": 0,
        "CattlePerished": 32,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 14,
        "DistrictName": "Shangla",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 13,
        "FemaleDeaths": 14,
        "ChildDeaths": 9,
        "TotalDeaths": 36,
        "MaleInjured": 11,
        "FemaleInjured": 6,
        "ChildInjured": 11,
        "TotalInjured": 28,
        "HouseDamagedFully": 150,
        "HouseDamagedPartially": 220,
        "TotalHousesDamaged": 370,
        "SchoolDamagedFully": 15,
        "SchoolDamagedPartially": 109,
        "TotalSchoolDamaged": 124,
        "TotalOtherDamaged": 5,
        "CattlePerished": 334,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 15,
        "DistrictName": "Swat",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 5,
        "FemaleDeaths": 2,
        "ChildDeaths": 13,
        "TotalDeaths": 20,
        "MaleInjured": 2,
        "FemaleInjured": 1,
        "ChildInjured": 2,
        "TotalInjured": 5,
        "HouseDamagedFully": 109,
        "HouseDamagedPartially": 442,
        "TotalHousesDamaged": 551,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 163,
        "TotalSchoolDamaged": 163,
        "TotalOtherDamaged": 18,
        "CattlePerished": 487,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 16,
        "DistrictName": "Upper Dir",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 3,
        "HouseDamagedPartially": 2,
        "TotalHousesDamaged": 5,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 3,
        "TotalSchoolDamaged": 3,
        "TotalOtherDamaged": 6,
        "CattlePerished": 1,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 17,
        "DistrictName": "Abbottabad",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 1,
        "FemaleDeaths": 1,
        "ChildDeaths": 0,
        "TotalDeaths": 2,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 19,
        "TotalHousesDamaged": 19,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 1,
        "CattlePerished": 6,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 18,
        "DistrictName": "Battagram",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 1,
        "FemaleDeaths": 1,
        "ChildDeaths": 1,
        "TotalDeaths": 3,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 5,
        "TotalHousesDamaged": 5,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 22,
        "DistrictName": "Mansehra",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 13,
        "FemaleDeaths": 9,
        "ChildDeaths": 3,
        "TotalDeaths": 25,
        "MaleInjured": 5,
        "FemaleInjured": 5,
        "ChildInjured": 0,
        "TotalInjured": 10,
        "HouseDamagedFully": 30,
        "HouseDamagedPartially": 103,
        "TotalHousesDamaged": 133,
        "SchoolDamagedFully": 2,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 2,
        "TotalOtherDamaged": 0,
        "CattlePerished": 23,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 23,
        "DistrictName": "Torghar",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 1,
        "ChildDeaths": 0,
        "TotalDeaths": 1,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 10,
        "TotalHousesDamaged": 10,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 11,
        "TotalSchoolDamaged": 11,
        "TotalOtherDamaged": 2,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 24,
        "DistrictName": "Upper Kohistan",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 1,
        "TotalDeaths": 1,
        "MaleInjured": 1,
        "FemaleInjured": 1,
        "ChildInjured": 1,
        "TotalInjured": 3,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 1,
        "TotalHousesDamaged": 1,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 26,
        "DistrictName": "Lakki Marwat",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 12,
        "HouseDamagedPartially": 59,
        "TotalHousesDamaged": 71,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 4,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 27,
        "DistrictName": "North Waziristan",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 1,
        "HouseDamagedPartially": 4,
        "TotalHousesDamaged": 5,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 28,
        "DistrictName": "Dera Ismail Khan",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 4,
        "FemaleDeaths": 2,
        "ChildDeaths": 2,
        "TotalDeaths": 8,
        "MaleInjured": 37,
        "FemaleInjured": 11,
        "ChildInjured": 10,
        "TotalInjured": 58,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 5,
        "TotalHousesDamaged": 5,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 30,
        "DistrictName": "Tank",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 13,
        "HouseDamagedPartially": 46,
        "TotalHousesDamaged": 59,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 32,
        "DistrictName": "Karak",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 2,
        "TotalHousesDamaged": 2,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 33,
        "DistrictName": "Kohat",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 0,
        "HouseDamagedPartially": 8,
        "TotalHousesDamaged": 8,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 34,
        "DistrictName": "Kurram",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 0,
        "ChildDeaths": 0,
        "TotalDeaths": 0,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 2,
        "HouseDamagedPartially": 2,
        "TotalHousesDamaged": 4,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    },
    {
        "ReportDate": null,
        "DistrictId": 37,
        "DistrictName": "South Waziristan Upper",
        "DivisionId": 0,
        "DivisionName": null,
        "Nat_Id": 0,
        "Nat_Name": null,
        "MaleDeaths": 0,
        "FemaleDeaths": 1,
        "ChildDeaths": 0,
        "TotalDeaths": 1,
        "MaleInjured": 0,
        "FemaleInjured": 0,
        "ChildInjured": 0,
        "TotalInjured": 0,
        "HouseDamagedFully": 8,
        "HouseDamagedPartially": 2,
        "TotalHousesDamaged": 10,
        "SchoolDamagedFully": 0,
        "SchoolDamagedPartially": 0,
        "TotalSchoolDamaged": 0,
        "TotalOtherDamaged": 0,
        "CattlePerished": 0,
        "total_dmis_deaths": 0,
        "total_dmis_injured": 0,
        "total_dmis_house_damaged": 0,
        "total_dmis_school_damaged": 0,
        "total_dmis_other_damaged": 0
    }
],

warehouseItemStocked:[
  {
      "key_id": 3,
      "item_value": 19683,
      "item_title": "Peshawar"
  },
  {
      "key_id": 6,
      "item_value": 50547,
      "item_title": "Hazara"
  },
  {
      "key_id": 7,
      "item_value": 16846,
      "item_title": " Dera Ismail Khan"
  },
  {
      "key_id": 4,
      "item_value": 4150,
      "item_title": "Mardan"
  },
  {
      "key_id": 5,
      "item_value": 12995,
      "item_title": "Kohat"
  },
  {
      "key_id": 2,
      "item_value": 85861,
      "item_title": "Malakand"
  },
  {
      "key_id": 8,
      "item_value": 6145,
      "item_title": "Bannu"
  }
],

districtsWiseCasualities:[
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 1,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 5,
      "TotalHousesDamaged": 5,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 5,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 6,
      "TotalHousesDamaged": 6,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-20",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 1,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-25",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-26",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 3,
      "TotalHousesDamaged": 3,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 1,
      "CattlePerished": 1,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-27",
      "DistrictId": 17,
      "DistrictName": "Abbottabad",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 8,
      "DistrictName": "Bajaur",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 2,
      "FemaleDeaths": 4,
      "ChildDeaths": 15,
      "TotalDeaths": 21,
      "MaleInjured": 1,
      "FemaleInjured": 4,
      "ChildInjured": 0,
      "TotalInjured": 5,
      "HouseDamagedFully": 3,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 3,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 2,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 8,
      "DistrictName": "Bajaur",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 1,
      "TotalDeaths": 1,
      "MaleInjured": 1,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 1,
      "HouseDamagedFully": 6,
      "HouseDamagedPartially": 61,
      "TotalHousesDamaged": 67,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 3,
      "TotalSchoolDamaged": 3,
      "TotalOtherDamaged": 4,
      "CattlePerished": 85,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 18,
      "DistrictName": "Battagram",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 1,
      "FemaleDeaths": 1,
      "ChildDeaths": 1,
      "TotalDeaths": 3,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 5,
      "TotalHousesDamaged": 5,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 63,
      "FemaleDeaths": 2,
      "ChildDeaths": 25,
      "TotalDeaths": 90,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-16",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 20,
      "ChildDeaths": 4,
      "TotalDeaths": 24,
      "MaleInjured": 58,
      "FemaleInjured": 62,
      "ChildInjured": 0,
      "TotalInjured": 120,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 8,
      "FemaleDeaths": 0,
      "ChildDeaths": 1,
      "TotalDeaths": 9,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 93,
      "ChildDeaths": 9,
      "TotalDeaths": 102,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 3,
      "TotalDeaths": 3,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 162,
      "HouseDamagedPartially": 575,
      "TotalHousesDamaged": 737,
      "SchoolDamagedFully": 1,
      "SchoolDamagedPartially": 28,
      "TotalSchoolDamaged": 29,
      "TotalOtherDamaged": 0,
      "CattlePerished": 4366,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-20",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 6,
      "TotalDeaths": 6,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 8,
      "TotalInjured": 8,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-21",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 3,
      "TotalDeaths": 3,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-22",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 111,
      "HouseDamagedPartially": 744,
      "TotalHousesDamaged": 855,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-27",
      "DistrictId": 9,
      "DistrictName": "Buner",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 3,
      "HouseDamagedPartially": 55,
      "TotalHousesDamaged": 58,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 39,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 4,
      "DistrictName": "Charsadda",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 1,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 1,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 3,
      "TotalHousesDamaged": 3,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 4,
      "DistrictName": "Charsadda",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 5,
      "TotalHousesDamaged": 6,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 28,
      "DistrictName": "Dera Ismail Khan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 4,
      "FemaleDeaths": 2,
      "ChildDeaths": 2,
      "TotalDeaths": 8,
      "MaleInjured": 37,
      "FemaleInjured": 11,
      "ChildInjured": 10,
      "TotalInjured": 58,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 5,
      "TotalHousesDamaged": 5,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 32,
      "DistrictName": "Karak",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 33,
      "DistrictName": "Kohat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 8,
      "TotalHousesDamaged": 8,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 34,
      "DistrictName": "Kurram",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 2,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 4,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 26,
      "DistrictName": "Lakki Marwat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 12,
      "HouseDamagedPartially": 59,
      "TotalHousesDamaged": 71,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 4,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 13,
      "DistrictName": "Lower Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 2,
      "ChildDeaths": 3,
      "TotalDeaths": 5,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 32,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-21",
      "DistrictId": 13,
      "DistrictName": "Lower Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 2,
      "HouseDamagedPartially": 43,
      "TotalHousesDamaged": 45,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 22,
      "DistrictName": "Mansehra",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 9,
      "FemaleDeaths": 9,
      "ChildDeaths": 3,
      "TotalDeaths": 21,
      "MaleInjured": 4,
      "FemaleInjured": 1,
      "ChildInjured": 0,
      "TotalInjured": 5,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-16",
      "DistrictId": 22,
      "DistrictName": "Mansehra",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 22,
      "HouseDamagedPartially": 14,
      "TotalHousesDamaged": 36,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 16,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 22,
      "DistrictName": "Mansehra",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 4,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 4,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 8,
      "HouseDamagedPartially": 89,
      "TotalHousesDamaged": 97,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-23",
      "DistrictId": 22,
      "DistrictName": "Mansehra",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-25",
      "DistrictId": 22,
      "DistrictName": "Mansehra",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 1,
      "FemaleInjured": 4,
      "ChildInjured": 0,
      "TotalInjured": 5,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 7,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 1,
      "DistrictName": "Mardan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 1,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 1,
      "DistrictName": "Mardan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 1,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 1,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 3,
      "TotalHousesDamaged": 4,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 1,
      "DistrictName": "Mardan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 3,
      "TotalHousesDamaged": 3,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 1,
      "DistrictName": "Mardan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 1,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 2,
      "FemaleInjured": 0,
      "ChildInjured": 1,
      "TotalInjured": 3,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 5,
      "TotalHousesDamaged": 5,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 7,
      "DistrictName": "Mohmand",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 1,
      "ChildInjured": 0,
      "TotalInjured": 1,
      "HouseDamagedFully": 4,
      "HouseDamagedPartially": 14,
      "TotalHousesDamaged": 18,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 1,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 7,
      "DistrictName": "Mohmand",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 27,
      "DistrictName": "North Waziristan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 27,
      "DistrictName": "North Waziristan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-25",
      "DistrictId": 27,
      "DistrictName": "North Waziristan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 5,
      "DistrictName": "Nowshera",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 1,
      "FemaleDeaths": 1,
      "ChildDeaths": 0,
      "TotalDeaths": 2,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 5,
      "DistrictName": "Nowshera",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 14,
      "DistrictName": "Shangla",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 12,
      "FemaleDeaths": 14,
      "ChildDeaths": 9,
      "TotalDeaths": 35,
      "MaleInjured": 1,
      "FemaleInjured": 1,
      "ChildInjured": 6,
      "TotalInjured": 8,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 8,
      "TotalHousesDamaged": 9,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 1,
      "TotalSchoolDamaged": 1,
      "TotalOtherDamaged": 3,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-16",
      "DistrictId": 14,
      "DistrictName": "Shangla",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 1,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 10,
      "FemaleInjured": 2,
      "ChildInjured": 0,
      "TotalInjured": 12,
      "HouseDamagedFully": 54,
      "HouseDamagedPartially": 32,
      "TotalHousesDamaged": 86,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 54,
      "TotalSchoolDamaged": 54,
      "TotalOtherDamaged": 0,
      "CattlePerished": 53,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 14,
      "DistrictName": "Shangla",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 3,
      "ChildInjured": 0,
      "TotalInjured": 3,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 1,
      "TotalSchoolDamaged": 1,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-21",
      "DistrictId": 14,
      "DistrictName": "Shangla",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 45,
      "HouseDamagedPartially": 64,
      "TotalHousesDamaged": 109,
      "SchoolDamagedFully": 15,
      "SchoolDamagedPartially": 18,
      "TotalSchoolDamaged": 33,
      "TotalOtherDamaged": 2,
      "CattlePerished": 50,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-22",
      "DistrictId": 14,
      "DistrictName": "Shangla",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 5,
      "TotalInjured": 5,
      "HouseDamagedFully": 50,
      "HouseDamagedPartially": 116,
      "TotalHousesDamaged": 166,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 23,
      "TotalSchoolDamaged": 23,
      "TotalOtherDamaged": 0,
      "CattlePerished": 206,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-27",
      "DistrictId": 14,
      "DistrictName": "Shangla",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 12,
      "TotalSchoolDamaged": 12,
      "TotalOtherDamaged": 0,
      "CattlePerished": 25,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 37,
      "DistrictName": "South Waziristan Upper",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 1,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 8,
      "HouseDamagedPartially": 2,
      "TotalHousesDamaged": 10,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 2,
      "DistrictName": "Swabi",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 6,
      "FemaleDeaths": 3,
      "ChildDeaths": 8,
      "TotalDeaths": 17,
      "MaleInjured": 3,
      "FemaleInjured": 2,
      "ChildInjured": 1,
      "TotalInjured": 6,
      "HouseDamagedFully": 9,
      "HouseDamagedPartially": 10,
      "TotalHousesDamaged": 19,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-19",
      "DistrictId": 2,
      "DistrictName": "Swabi",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 7,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 7,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-20",
      "DistrictId": 2,
      "DistrictName": "Swabi",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 6,
      "FemaleDeaths": 11,
      "ChildDeaths": 1,
      "TotalDeaths": 18,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 38,
      "HouseDamagedPartially": 51,
      "TotalHousesDamaged": 89,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 1,
      "TotalSchoolDamaged": 1,
      "TotalOtherDamaged": 0,
      "CattlePerished": 31,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 15,
      "DistrictName": "Swat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 4,
      "FemaleDeaths": 2,
      "ChildDeaths": 13,
      "TotalDeaths": 19,
      "MaleInjured": 2,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 2,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 49,
      "TotalHousesDamaged": 50,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 2,
      "TotalSchoolDamaged": 2,
      "TotalOtherDamaged": 13,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 15,
      "DistrictName": "Swat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 1,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 42,
      "HouseDamagedPartially": 128,
      "TotalHousesDamaged": 170,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-21",
      "DistrictId": 15,
      "DistrictName": "Swat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 23,
      "HouseDamagedPartially": 41,
      "TotalHousesDamaged": 64,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 161,
      "TotalSchoolDamaged": 161,
      "TotalOtherDamaged": 5,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-22",
      "DistrictId": 15,
      "DistrictName": "Swat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 22,
      "HouseDamagedPartially": 45,
      "TotalHousesDamaged": 67,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-26",
      "DistrictId": 15,
      "DistrictName": "Swat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 14,
      "HouseDamagedPartially": 145,
      "TotalHousesDamaged": 159,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-27",
      "DistrictId": 15,
      "DistrictName": "Swat",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 1,
      "ChildInjured": 2,
      "TotalInjured": 3,
      "HouseDamagedFully": 7,
      "HouseDamagedPartially": 34,
      "TotalHousesDamaged": 41,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 487,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 30,
      "DistrictName": "Tank",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 13,
      "HouseDamagedPartially": 46,
      "TotalHousesDamaged": 59,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 23,
      "DistrictName": "Torghar",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 3,
      "TotalHousesDamaged": 3,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-16",
      "DistrictId": 23,
      "DistrictName": "Torghar",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 23,
      "DistrictName": "Torghar",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 23,
      "DistrictName": "Torghar",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 1,
      "ChildDeaths": 0,
      "TotalDeaths": 1,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 5,
      "TotalHousesDamaged": 5,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-20",
      "DistrictId": 23,
      "DistrictName": "Torghar",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 11,
      "TotalSchoolDamaged": 11,
      "TotalOtherDamaged": 2,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-15",
      "DistrictId": 16,
      "DistrictName": "Upper Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 1,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-16",
      "DistrictId": 16,
      "DistrictName": "Upper Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 3,
      "TotalSchoolDamaged": 3,
      "TotalOtherDamaged": 6,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 16,
      "DistrictName": "Upper Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 1,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 2,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-18",
      "DistrictId": 16,
      "DistrictName": "Upper Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 0,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-24",
      "DistrictId": 16,
      "DistrictName": "Upper Dir",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-23",
      "DistrictId": 24,
      "DistrictName": "Upper Kohistan",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 1,
      "TotalDeaths": 1,
      "MaleInjured": 1,
      "FemaleInjured": 1,
      "ChildInjured": 1,
      "TotalInjured": 3,
      "HouseDamagedFully": 0,
      "HouseDamagedPartially": 1,
      "TotalHousesDamaged": 1,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  },
  {
      "ReportDate": "2025-08-17",
      "DistrictId": 11,
      "DistrictName": "Upper-Chitral",
      "DivisionId": 0,
      "DivisionName": null,
      "Nat_Id": 0,
      "Nat_Name": null,
      "MaleDeaths": 0,
      "FemaleDeaths": 0,
      "ChildDeaths": 0,
      "TotalDeaths": 0,
      "MaleInjured": 0,
      "FemaleInjured": 0,
      "ChildInjured": 0,
      "TotalInjured": 0,
      "HouseDamagedFully": 5,
      "HouseDamagedPartially": 0,
      "TotalHousesDamaged": 5,
      "SchoolDamagedFully": 0,
      "SchoolDamagedPartially": 0,
      "TotalSchoolDamaged": 0,
      "TotalOtherDamaged": 0,
      "CattlePerished": 0,
      "total_dmis_deaths": 0,
      "total_dmis_injured": 0,
      "total_dmis_house_damaged": 0,
      "total_dmis_school_damaged": 0,
      "total_dmis_other_damaged": 0
  }
],
  // Monetary Loss Rates (in PKR)
  monetaryLossRates: {
    "House Fully": 7352000000.0,
    "House Partially": 8589000000.0,
    "Big cattles": 937763103.96,
    "small Cattles": 351280000.0,
    "Educational Facilities Damaged fully": 2083000000.0,
    "Educational Facilities Damaged Partially": 987000000.0,
    "HED facilities Damaged": 14400000.0,
    "Public Offices": 603000000.0,
    "Shops": 3220000000.0,
    "Roads in Km restoration": 463303536.0,
    "Roads in Km rehabiliation": 2701011831.0,
    "Bridges in meter restoration": 6226780.0,
    "Bridges in meter rehabiliation": 49483704.0,
    "Culverts in Meter restoration": 1628175.0,
    "Culverts in Meter rehabiliation": 5780225.0,
    "Vehicles": 300000000.0,
    "Health facilities": 320000000.0,
    "Fodders roughes": 126270000.0,
    "Fodders concentrate": 20842500.0,
    "Shelters": 252000000.0,
    "Crops destruction": 6418850000.0,
    "Transformers": 2000000000.0,
    "services": 100658000.0,
    "Local government": 1008000000.0,
    "Energy and Power": 402000000.0,
    "irrigation": 9227000000.0,
    "public health": 1070000000.0
  },

  // Compensation Rates (in PKR)
  compensationRates: [
    { type: "Death", amount: 2000000, category: "casualties" },
    { type: "Injury", amount: 500000, category: "casualties" },
    { type: "Grievous Injury", amount: 300000, category: "casualties" },
    { type: "Substantial Injury", amount: 50000, category: "casualties" },
    { type: "Fully Damaged Houses", amount: 1000000, category: "property" },
    { type: "Partial damaged Houses", amount: 300000, category: "property" },
    { type: "Petrol Pump", amount: 1500000, category: "business" },
    { type: "Shops, Kiosk or other business establishment Fully Damaged", amount: 500000, category: "business" },
    { type: "Shops, Kiosk or other business establishment Partial Damaged", amount: 150000, category: "business" },
    { type: "Heavy Vehicle Fully Damaged", amount: 200000, category: "vehicle" },
    { type: "Heavy Vehicle Partial Damaged", amount: 100000, category: "vehicle" },
    { type: "Car, jeep 4 or 3 Wheelers Fully Damaged", amount: 300000, category: "vehicle" },
    { type: "Car, jeep 4 or 3 Wheelers Partial Damaged", amount: 60000, category: "vehicle" },
    { type: "Motorcycle or Scooter", amount: 40000, category: "vehicle" },
    { type: "Big Cattles (cows,buffalos,Horse)", amount: 80000, category: "livestock" },
    { type: "Small Cattles(Donkey,Goat, Sheep)", amount: 20000, category: "livestock" },
    { type: "Crops per acre", amount: 5000, category: "agricultural" },
    { type: "Crops per family", amount: 50000, category: "agricultural" },
    { type: "Orchads per Family", amount: 40000, category: "agricultural" },
    { type: "Tree per unit", amount: 400, category: "agricultural" },
    { type: "Family Ration Support", amount: 15000, category: "support" }
  ],

  // Compensation Data (Actual counts and totals)
  compensationData: [
    { type: "Death", compensation: 2000000, count: 406, total: 812000000 },
    { type: "Injury", compensation: 500000, count: 248, total: 124000000 },
    { type: "Partial damaged Houses", compensation: 300000, count: 2683, total: 804900000 },
    { type: "Fully Damaged Houses", compensation: 1000000, count: 978, total: 978000000 },
    { type: "Shops, Kiosk or other business establishment Fully Damaged", compensation: 500000, count: 1288, total: 644000000 },
    { type: "Vehicle Fully Damaged", compensation: 300000, count: 100, total: 30000000 },
    { type: "Big Cattles (cows,buffalos,Horse)", compensation: 80000, count: 3972, total: 317760000 },
    { type: "Small Cattles(Donkey,Goat, Sheep", compensation: 20000, count: 8782, total: 175640000 },
    { type: "Crops per acre", compensation: 5000, count: 57892.5, total: 289462500 }
  ],

  // Key Statistics Summary (Updated with incident data)
  summaryStats: {
    totalMonetaryLoss: 48610497854.96, // Rs 48.61B
    totalCompensation: 4180000000, // Rs 4.18B (static value)
    totalDeaths: 406,
    totalInjured: 248,
    totalHousesDamaged: 3661, // 978 fully + 2683 partially
    totalCattleLost: 12725,
    totalCropAreaAffected: 1302617.3, // acres
    affectedDistricts: 15,
    reportPeriod: {
      from: "2025-08-22",
      to: "2025-08-29"
    },
    // Incident-based statistics
    incidentStats: {
      totalDistrictsWithIncidents: 25,
      totalDeathsByGender: { male: 134, female: 162, children: 110 },
      totalInjuredByGender: { male: 125, female: 95, children: 28 },
      totalHousesDamagedByType: { fully: 978, partially: 2683 },
      totalSchoolsDamagedByType: { fully: 18, partially: 306 },
      totalCattlePerished: 5486
    }
  },

  // Most Affected Districts Analysis (Updated with incident data)
  mostAffectedDistricts: [
    {
      name: "Buner",
      reasons: [
        "Highest deaths: 237 (71 male, 115 female, 51 children)",
        "Highest agricultural losses: Rs 2.36B",
        "Significant livestock losses: 4,405 cattle perished",
        "Infrastructure damage: 45km roads, 4 culverts",
        "Low restoration progress: 47%",
        "1,650 houses damaged (276 fully, 1,374 partially)"
      ],
      deaths: { total: 237, male: 71, female: 115, children: 51 },
      injured: { total: 128, male: 58, female: 62, children: 8 },
      agriculturalLosses: 2363700000,
      livestockLosses: 4405,
      infrastructureDamage: { roadsKm: 45, bridges: 0, culverts: 4 },
      housesDamaged: { total: 1650, fully: 276, partially: 1374 },
      schoolsDamaged: { total: 29, fully: 1, partially: 28 }
    },
    {
      name: "Swabi",
      reasons: [
        "Second highest deaths: 42 (19 male, 14 female, 9 children)",
        "High livestock losses: 31 cattle perished",
        "108 houses damaged (47 fully, 61 partially)",
        "Infrastructure damage: 10km roads, 4 bridges, 11 culverts"
      ],
      deaths: { total: 42, male: 19, female: 14, children: 9 },
      injured: { total: 6, male: 3, female: 2, children: 1 },
      livestockLosses: 31,
      infrastructureDamage: { roadsKm: 10, bridges: 4, culverts: 11 },
      housesDamaged: { total: 108, fully: 47, partially: 61 },
      schoolsDamaged: { total: 1, fully: 0, partially: 1 }
    },
    {
      name: "Shangla",
      reasons: [
        "Third highest deaths: 36 (13 male, 14 female, 9 children)",
        "Infrastructure damage: 20km roads, 1 culvert",
        "Agricultural losses: Rs 8.18M",
        "370 houses damaged (150 fully, 220 partially)",
        "124 schools damaged (15 fully, 109 partially)"
      ],
      deaths: { total: 36, male: 13, female: 14, children: 9 },
      injured: { total: 28, male: 11, female: 6, children: 11 },
      agriculturalLosses: 8180000,
      livestockLosses: 334,
      infrastructureDamage: { roadsKm: 20, bridges: 0, culverts: 1 },
      housesDamaged: { total: 370, fully: 150, partially: 220 },
      schoolsDamaged: { total: 124, fully: 15, partially: 109 }
    },
    {
      name: "Swat",
      reasons: [
        "20 deaths (5 male, 2 female, 13 children)",
        "Large agricultural area affected: 392K acres",
        "551 houses damaged (109 fully, 442 partially)",
        "163 schools damaged (0 fully, 163 partially)",
        "Infrastructure damage: 67km roads, 9 bridges"
      ],
      deaths: { total: 20, male: 5, female: 2, children: 13 },
      injured: { total: 5, male: 2, female: 1, children: 2 },
      agriculturalArea: 392127.32,
      livestockLosses: 487,
      infrastructureDamage: { roadsKm: 67, bridges: 9, culverts: 4 },
      housesDamaged: { total: 551, fully: 109, partially: 442 },
      schoolsDamaged: { total: 163, fully: 0, partially: 163 }
    },
    {
      name: "Mansehra",
      reasons: [
        "25 deaths (13 male, 9 female, 3 children)",
        "High agricultural losses: Rs 777M",
        "133 houses damaged (30 fully, 103 partially)",
        "Infrastructure damage: 31km roads, 2 bridges"
      ],
      deaths: { total: 25, male: 13, female: 9, children: 3 },
      injured: { total: 10, male: 5, female: 5, children: 0 },
      agriculturalLosses: 777803000,
      livestockLosses: 23,
      infrastructureDamage: { roadsKm: 31, bridges: 2, culverts: 1 },
      housesDamaged: { total: 133, fully: 30, partially: 103 },
      schoolsDamaged: { total: 2, fully: 2, partially: 0 }
    }
  ],

  // Infrastructure Impact Summary
  infrastructureImpact: {
    totalRoadsDamaged: 279, // km
    totalBridgesDamaged: 26,
    totalCulvertsDamaged: 32,
    districtsWithDamage: 15,
    restorationProgress: {
      completed: ["Bannu", "Charsadda", "Kurram", "Lakki Marwat", "Mardan", "Mohmand", "North Waziristan", "Nowhsera", "Peshawar", "South Waziristan", "Torghar"],
      inProgress: ["Abbotabad", "Bajaur", "Battagram", "Buner", "Chitral Lower", "Chitral Upper", "Dera Ismail Khan", "Dir Lower", "Dir Upper", "Haripur", "Karak", "Malakand", "Mansehra", "Shangla", "Swabi", "Swat"]
    }
  },

  // Agricultural Impact Summary
  agriculturalImpact: {
    totalCropAreaAffected: 1302617.3, // acres
    totalEstimatedLosses: 6418849500, // Rs 6.42B
    districtsWithLosses: 15,
    topLosses: [
      { district: "Buner", losses: 2363700000 },
      { district: "Mansehra", losses: 777803000 },
      { district: "Dir Lower", losses: 505362000 },
      { district: "Swabi", losses: 629600000 },
      { district: "Malakand", losses: 528800000 }
    ]
  },

  // Livestock Impact Summary
  livestockImpact: {
    totalCattlePerished: 12725,
    bigCattle: 3972,
    smallCattle: 8782,
    fodderRoughages: 4209, // tons
    fodderConcentrates: 119100, // kg
    sheltersDamaged: 252,
    affectedDistricts: 6,
    districtBreakdown: [
      { district: "Buner", cattlesPerished: 11202, bigCattle: 3022, smallCattle: 8180 },
      { district: "Swat", cattlesPerished: 1044, bigCattle: 781, smallCattle: 263 },
      { district: "Shangla", cattlesPerished: 243, bigCattle: 99, smallCattle: 144 },
      { district: "Bajaur", cattlesPerished: 180, bigCattle: 30, smallCattle: 150 },
      { district: "Battagram", cattlesPerished: 31, bigCattle: 31, smallCattle: 29 },
      { district: "Dir Lower", cattlesPerished: 25, bigCattle: 9, smallCattle: 16 }
    ]
  },

  // Data Analysis Functions for Seamless Queries
  dataAnalysis: {
    // Get district by name with all data
    getDistrictData: (districtName: string) => {
      const incidentData = KP_FLOODS_STATIC_DATA.incidentReport.find(
        d => d.DistrictName?.toLowerCase() === districtName.toLowerCase()
      );
      const casualtiesData = KP_FLOODS_STATIC_DATA.districtsWiseCasualities.filter(
        d => d.DistrictName?.toLowerCase() === districtName.toLowerCase()
      );
      return { incidentData, casualtiesData };
    },

    // Get top districts by any metric
    getTopDistricts: (metric: 'deaths' | 'injured' | 'houses' | 'cattle' | 'schools', limit: number = 5) => {
      const sorted = [...KP_FLOODS_STATIC_DATA.incidentReport].sort((a, b) => {
        switch (metric) {
          case 'deaths': return (b.TotalDeaths || 0) - (a.TotalDeaths || 0);
          case 'injured': return (b.TotalInjured || 0) - (a.TotalInjured || 0);
          case 'houses': return (b.TotalHousesDamaged || 0) - (a.TotalHousesDamaged || 0);
          case 'cattle': return (b.CattlePerished || 0) - (a.CattlePerished || 0);
          case 'schools': return (b.TotalSchoolDamaged || 0) - (a.TotalSchoolDamaged || 0);
          default: return 0;
        }
      });
      return sorted.slice(0, limit);
    },

    // Get daily trends for a district
    getDailyTrends: (districtName: string) => {
      return KP_FLOODS_STATIC_DATA.districtsWiseCasualities.filter(
        d => d.DistrictName?.toLowerCase() === districtName.toLowerCase()
      ).sort((a, b) => new Date(a.ReportDate).getTime() - new Date(b.ReportDate).getTime());
    },

    // Get warehouse stock by division
    getWarehouseStock: (divisionName?: string) => {
      if (divisionName) {
        return KP_FLOODS_STATIC_DATA.warehouseItemStocked.find(
          w => w.item_title?.toLowerCase().includes(divisionName.toLowerCase())
        );
      }
      return KP_FLOODS_STATIC_DATA.warehouseItemStocked;
    },

    // Calculate percentages and ratios
    calculatePercentages: () => {
      const totalDeaths = KP_FLOODS_STATIC_DATA.incidentReport.reduce((sum, d) => sum + (d.TotalDeaths || 0), 0);
      const totalInjured = KP_FLOODS_STATIC_DATA.incidentReport.reduce((sum, d) => sum + (d.TotalInjured || 0), 0);
      const totalHouses = KP_FLOODS_STATIC_DATA.incidentReport.reduce((sum, d) => sum + (d.TotalHousesDamaged || 0), 0);
      
      return {
        deathToInjuryRatio: totalDeaths / totalInjured,
        averageDeathsPerDistrict: totalDeaths / KP_FLOODS_STATIC_DATA.incidentReport.length,
        averageHousesPerDistrict: totalHouses / KP_FLOODS_STATIC_DATA.incidentReport.length
      };
    },

    // Get comprehensive district summary
    getDistrictSummary: (districtName: string) => {
      const district = KP_FLOODS_STATIC_DATA.incidentReport.find(
        d => d.DistrictName?.toLowerCase() === districtName.toLowerCase()
      );
      const mostAffected = KP_FLOODS_STATIC_DATA.mostAffectedDistricts.find(
        d => d.name.toLowerCase() === districtName.toLowerCase()
      );
      const warehouse = KP_FLOODS_STATIC_DATA.warehouseItemStocked.find(
        w => w.item_title?.toLowerCase().includes(districtName.toLowerCase())
      );
      
      return { district, mostAffected, warehouse };
    }
  }
};

export async function sendAssistantMessage(request: AssistantRequest): Promise<AssistantResponse> {
  // Merge static data with dynamic data and add query guidance
  const enhancedData = {
    ...request.data,
    staticData: KP_FLOODS_STATIC_DATA,
    queryGuide: {
      // Available data sources
      dataSources: {
        incidentReport: "Complete incident data for all districts with deaths, injuries, damages",
        districtsWiseCasualities: "Daily casualty trends by district with dates",
        warehouseItemStocked: "Warehouse stock levels by division",
        monetaryLossRates: "Detailed monetary loss rates for all categories",
        compensationRates: "Compensation rates for different damage types",
        mostAffectedDistricts: "Pre-analyzed most affected districts with reasons"
      },
      
      // Common query patterns
      queryPatterns: {
        "Which districts were most affected?": "Use mostAffectedDistricts array or getTopDistricts('deaths')",
        "How many people died in [district]?": "Use getDistrictData(districtName) or incidentReport",
        "What are the daily trends for [district]?": "Use getDailyTrends(districtName)",
        "What is the warehouse stock in [division]?": "Use getWarehouseStock(divisionName)",
        "What is the total monetary loss?": "Use summaryStats.totalMonetaryLoss",
        "How many houses were damaged?": "Use summaryStats.incidentStats.totalHousesDamagedByType",
        "What are the compensation rates?": "Use compensationRates array",
        "Show me the top 5 districts by [metric]": "Use getTopDistricts(metric, 5)"
      },
      
      // Key insights to highlight
      keyInsights: {
        "Buner is the most affected": "237 deaths, 1,650 houses damaged, Rs 2.36B agricultural losses",
        "Swabi has second highest deaths": "42 deaths, 108 houses damaged",
        "Shangla has most school damage": "124 schools damaged (15 fully, 109 partially)",
        "Swat has largest agricultural impact": "392K acres affected, 551 houses damaged",
        "Gender distribution": "More female deaths (162) than male (134), more children deaths (110)",
        "Infrastructure impact": "279km roads, 26 bridges, 32 culverts damaged across 15 districts"
      }
    }
  };

  const payload = {
    prompt: request.prompt,
    data: enhancedData,
    model: request.model || 'gpt-4o-mini',
    max_tokens: request.max_tokens || 1000,
    temperature: request.temperature || 0.7
  };

  return api<AssistantResponse>('/assistant/chat', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
} 